package com.opsflow.domain.enums;

public enum AuditAction {
    SERVICE_REQUEST_CREATED,
    SERVICE_REQUEST_TRIAGED,
    JOB_CREATED,
    JOB_TRIAGED,
    JOB_ASSIGNED,
    JOB_REASSIGNED,
    TECHNICIAN_ACCEPTED,
    TECHNICIAN_REJECTED,
    INVENTORY_RESERVED,
    INVENTORY_CONSUMED,
    INVENTORY_RELEASED,
    JOB_STARTED,
    JOB_COMPLETED,
    JOB_CANCELLED,
    SLA_WARNING_TRIGGERED,
    SLA_BREACHED
}
